src/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AssertException</fullName>
            </value>
            <value>
                <fullName>AuraException</fullName>
            </value>
            <value>
                <fullName>AuraHandledException</fullName>
            </value>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DataWeaveScriptException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>DuplicateMessageException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>FatalCursorException</fullName>
            </value>
            <value>
                <fullName>FinalException</fullName>
            </value>
            <value>
                <fullName>FlowException</fullName>
            </value>
            <value>
                <fullName>HandledException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidHeaderException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Interface</fullName>
            </value>
            <value>
                <fullName>Batch Job</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Scheduled Job</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Inaccessible_Fields__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields__c</fullName>
    <label>Inaccessible Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/classes/error-logger/ErrorLoggerTest.cls
/**
 * Test class for ErrorLog Class.
 * @author Christopher Pezza (@chiefpansancolt)
 * @since 2024-11-24
 * @group Tests
 */
@IsTest(IsParallel=false)
private with sharing class ErrorLoggerTest {
	/**
	 * A Test Exception extending Exception
	 */
	private class TestException extends Exception {
		/* No implementation needed */
	}

	@IsTest
	private static void shouldNotRunInTestMode() {
		TestException testException = new TestException('Test Exception Message');

		Test.startTest();
		ErrorLogger.logError(testException);
		Test.stopTest();

		List<Error_Log__c> results = TriggerFrameworkTestQueryFactory.getErrorLogs();
		Assert.areEqual(0, results.size(), 'No error log should have been created.');
	}

	@IsTest
	private static void shouldLogErrorWithExceptionOnly() {
		ErrorLogger.isTestMode = true;
		TestException testException = new TestException('Test Exception Message');

		Test.startTest();
		ErrorLogger.logError(testException);
		Test.stopTest();

		List<Error_Log__c> results = TriggerFrameworkTestQueryFactory.getErrorLogs();
		Assert.areEqual(1, results.size(), 'One error log should have been created.');
		Assert.areEqual('ErrorLoggerTest.TestException', results[0].Error_Type__c, 'Error type should match the exception type.');
		Assert.areEqual('Test Exception Message', results[0].Error_Message__c, 'Error message should match.');
		Assert.isNotNull(results[0].Stack_Trace__c, 'Stack trace should not be null.');
		Assert.isNotNull(results[0].Execution_Context__c, 'Execution context should not be null.');
	}

	@IsTest
	private static void shouldLogErrorWithExceptionAndClassName() {
		ErrorLogger.isTestMode = true;
		TestException testException = new TestException('Another Test Exception');
		String className = 'MyTestClass';

		Test.startTest();
		ErrorLogger.logError(testException, className);
		Test.stopTest();

		List<Error_Log__c> results = TriggerFrameworkTestQueryFactory.getErrorLogs();
		Assert.areEqual(1, results.size(), 'One error log should have been created.');
		Assert.areEqual('MyTestClass', results[0].Class_Name__c, 'Class name should match the provided value.');
	}

	@SuppressWarnings('PMD.UnusedLocalVariable')
	@IsTest
	private static void shouldLogErrorWithQueryException() {
		ErrorLogger.isTestMode = true;
		User testUser = TriggerFrameworkTestDataFactory.createUser();
		TriggerFrameworkTestDataFactory.createAccount('Test Account', true);

		System.runAs(testUser) {
			Test.startTest();

			try {
				List<Lead> testLead = [SELECT GenderIdentity FROM Lead WITH USER_MODE LIMIT 1];
			} catch (Exception e) {
				ErrorLogger.logError(e);
			}
			Test.stopTest();

			List<Error_Log__c> results = TriggerFrameworkTestQueryFactory.getErrorLogs();
			Assert.areEqual(1, results.size(), 'One error log should have been created.');
			Assert.isNotNull(results[0].Inaccessible_Fields__c, 'Inaccessible fields should be logged for QueryException.');
		}
	}
}