src/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AssertException</fullName>
            </value>
            <value>
                <fullName>AuraException</fullName>
            </value>
            <value>
                <fullName>AuraHandledException</fullName>
            </value>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DataWeaveScriptException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>DuplicateMessageException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>FatalCursorException</fullName>
            </value>
            <value>
                <fullName>FinalException</fullName>
            </value>
            <value>
                <fullName>FlowException</fullName>
            </value>
            <value>
                <fullName>HandledException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidHeaderException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Interface</fullName>
            </value>
            <value>
                <fullName>Batch Job</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Scheduled Job</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Inaccessible_Fields__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields__c</fullName>
    <label>Inaccessible Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Error_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/error-logger/ErrorLogger.cls
public with sharing class ErrorLogger {
    public static void logError(Exception e) {
        logError(e, null);
    }

	public static void logError(Exception e, String className) {
        if (!Test.isRunningTest()) {
            try {
                Error_Log__c errorLog = new Error_Log__c();
                errorLog.Error_Type__c = e.getTypeName();
                errorLog.Error_Message__c = e.getMessage();
                errorLog.Stack_Trace__c = e.getStackTraceString();
                errorLog.Timestamp__c = System.now();
                errorLog.Execution_Context__c = getExecutionContext();
                errorLog.User__c = UserInfo.getUserId();

                if (className != null) {
                    errorLog.Class_Name__c = className;
                }

                Exception cause = (Exception)e.getCause();
                if (cause != null) {
                    errorLog.Error_Cause__c = cause.getMessage();
                }

                if (e instanceof QueryException) {
                    QueryException queryException = (QueryException)e;
                    Map<String, Set<String>> inaccessible = queryException.getInaccessibleFields();
                    Set<String> fields = new Set<String>();

                    for (String objectName : inaccessible.keySet()) {
                        for(String field : inaccessible.get(objectName)) {
                            fields.add(objectName + '.' + field);
                        }
                    }

                    errorLog.Inaccessible_Fields__c = String.join(fields, ' | ');
                }

                Database.insert(errorLog);
            } catch (Exception loggingException) {
                System.debug('Failed to log the original error: ' + loggingException.getMessage());
                System.debug('Original Error: ' + e.getMessage());
            }
        }
	}

	private static String getExecutionContext() {
		if (System.isBatch()) {
			return 'Batch Job';
        } else if (System.isFuture()) {
			return 'Future';
        } else if (System.isQueueable()) {
			return 'Queueable';
        } else if (System.isScheduled()) {
			return 'Scheduled Job';
        } else if (Trigger.isExecuting) {
            return 'Trigger';
        }
		return 'User Interface';
	}
}