src/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AssertException</fullName>
            </value>
            <value>
                <fullName>AuraException</fullName>
            </value>
            <value>
                <fullName>AuraHandledException</fullName>
            </value>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DataWeaveScriptException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>DuplicateMessageException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>FatalCursorException</fullName>
            </value>
            <value>
                <fullName>FinalException</fullName>
            </value>
            <value>
                <fullName>FlowException</fullName>
            </value>
            <value>
                <fullName>HandledException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidHeaderException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Execution_Context__c.field-meta.xml
<CustomField>
    <fullName>Execution_Context__c</fullName>
    <label>Execution Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Interface</fullName>
            </value>
            <value>
                <fullName>Batch Job</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Scheduled Job</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/Inaccessible_Fields__c.field-meta.xml
<CustomField>
    <fullName>Inaccessible_Fields__c</fullName>
    <label>Inaccessible Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Error_Log__c/fields/Related_Record__c.field-meta.xml
<CustomField>
    <fullName>Related_Record__c</fullName>
    <label>Related Record</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Error_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Issue Identified</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Error_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Test_Object__c/Test_Object__c.object-meta.xml
<CustomObject>
    <description>Used for Testing Code for Trigger Framework</description>
    <label>Test Object</label>
    <nameField>
        <label>Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/test-utilities/TriggerFrameworkTestQueryFactory.cls
/**
 * Query Factory for Test Classes for common queries run in test classes.
 * @author Christopher Pezza (@chiefpansancolt)
 * @since 2024-11-24
 * @group Test Utilities
 */
@IsTest
public with sharing class TriggerFrameworkTestQueryFactory {
	/**
	 * Query all Error Logs created
	 * @return  `List<Error_Log__c>`
	 */
    public static List<Error_Log__c> getErrorLogs() {
		return [
			SELECT
				Id,
				Name,
				Class_Name__c,
				Error_Cause__c,
				Error_Message__c,
				Error_Severity__c,
				Error_Type__c,
				Execution_Context__c,
				Inaccessible_Fields__c,
				Line_Number__c,
				Related_Record__c,
				Stack_Trace__c,
				Status__c,
				Timestamp__c,
				User__c
			FROM Error_Log__c
		];
	}

	/**
	 * Get list of all Accounts.
	 * @return  `List<Account>`
	 */	
	public static List<Account> getAccounts() {
		return [SELECT Id, Name FROM Account];
	}

	/**
	 * Method to return Count of Test Objects
	 * @return  `Decimal`
	 */	
	public static Decimal getTestObjectCount() {
		return [SELECT COUNT() FROM Test_Object__c];
	}


	/**
	 * Method to return Name of Test Object
	 * @return  `String`
	 */
	public static String getTestObjectName() {
		return [SELECT Name FROM Test_Object__c][0].Name;
	}
}